list=[]
list1=int(input("enter your 1st iteam:-"))
list2=int(input("enter your 2st iteam:-"))
list3=int(input("enter your 3st iteam:-"))
list4=int(input("enter your 4st iteam:-"))
list5=int(input("enter your 5st iteam:-"))
list6=int(input("enter your 6st iteam:-"))
list7=int(input("enter your 7st iteam:-"))
list8=int(input("enter your 8st iteam:-"))
list9=int(input("enter your 9st iteam:-"))
list10=int(input("enter your 10st iteam:-"))
list11=int(input("enter your 11st iteam:-"))
list12=int(input("enter your 12st iteam:-"))
list13=int(input("enter your 13st iteam:-"))
list14=int(input("enter your 14st iteam:-"))
list15=int(input("enter your 15st iteam:-"))
list16=int(input("enter your 16st iteam:-"))
list17=int(input("enter your 17st iteam:-"))
list18=int(input("enter your 18st iteam:-"))
list19=int(input("enter your 19st iteam:-"))
list.append(list1)
list.append(list2)
list.append(list3)
list.append(list4)
list.append(list5)
list.append(list6)
list.append(list7)
list.append(list8)
list.append(list9)
list.append(list10)
list.append(list11)
list.append(list12)
list.append(list13)
list.append(list14)
list.append(list15)
list.append(list16)
list.append(list17)
list.append(list18)
list.append(list19)
print(list)



################
print()


list=[]
list1=int(input("enter your 1st iteam:-"))
list2=int(input("enter your 2st iteam:-"))
list3=int(input("enter your 3st iteam:-"))
list4=int(input("enter your 4st iteam:-"))
list5=int(input("enter your 5st iteam:-"))
list6=int(input("enter your 6st iteam:-"))
list7=int(input("enter your 7st iteam:-"))
list8=int(input("enter your 8st iteam:-"))
list9=int(input("enter your 9st iteam:-"))
list10=int(input("enter your 10st iteam:-"))
list11=int(input("enter your 11st iteam:-"))
list12=int(input("enter your 12st iteam:-"))
list13=int(input("enter your 13st iteam:-"))
list14=int(input("enter your 14st iteam:-"))
list15=int(input("enter your 15st iteam:-"))
list16=int(input("enter your 16st iteam:-"))
list17=int(input("enter your 17st iteam:-"))
list18=int(input("enter your 18st iteam:-"))
list19=int(input("enter your 19st iteam:-"))
list.append(list1)
list.append(list2)
list.append(list3)
list.append(list4)
list.append(list5)
list.append(list6)
list.append(list7)
list.append(list8)
list.append(list9)
list.append(list10)
list.append(list11)
list.append(list12)
list.append(list13)
list.append(list14)
list.append(list15)
list.append(list16)
list.append(list17)
list.append(list18)
list.append(list19)
print(list)
sum=0
for item in list:
    sum=sum+item
print("sum all iteam:--",sum)



print()
#sort-cut for sum of all iteam in list
###file name = list22222 Write a Program(WAP) to find the sum of all elements in a list
